### ISSUE TITLE
Webcam close and open

### ISSUE THREAD

**Issue by pacioc193** [eduramiba/webcam-capture-driver-native#4] opened 2021-12-20 17:13 UTC
After having close and open a webcam is not possible to open anymore!

This is the code :
`
Webcam.setDriver(new CaptureManagerDriver());
 Webcam webcam = Webcam.getWebcams().get(4);

        long t1, t2;

        for (int i = 0; i < 5; i++) {

            try {
                System.out.format("Opening...\n");

                t1 = System.currentTimeMillis();
                webcam.open();
                t2 = System.currentTimeMillis();

                System.out.format("Opening time: %d ms\n", t2 - t1);
                System.out.format("Fetch image...\n");

                t1 = System.currentTimeMillis();
                if (webcam.getImage() == null) {
                    System.err.println("Damn! Image is null!");
                }
                t2 = System.currentTimeMillis();

                System.out.format("Fetch image time: %d ms\n", t2 - t1);
                System.out.format("Closing...\n");

                t1 = System.currentTimeMillis();
                webcam.close();
                t2 = System.currentTimeMillis();

                System.out.format("Closing time: %d ms\n", t2 - t1);
                System.out.format("Wait 5 seconds...\n", t2 - t1);

                Thread.sleep(5000);
            } catch (InterruptedException ex) {
                java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }

        System.out.format("Done...\n");
`
![image](https://user-images.githubusercontent.com/3874577/146805894-669cb0c1-21a6-4606-b97c-93684bc03a3f.png)

Without the loading of the driver

![image](https://user-images.githubusercontent.com/3874577/146806000-60218b78-d857-486a-a12a-6d6e0526d6fd.png)

**Comment by pacioc193** [comment] 2021-12-21 08:13
It is stuck and can't open anymore the USB webcam...

**Comment by pacioc193** [comment] 2021-12-21 15:40
Debugging the software seems that after having close the webcam, open command will call automatically the original driver and not the loaded one.

I will try to continue to investigate...

**Comment by pacioc193** [comment] 2021-12-21 16:33
Closing procedure called from the driver is not closing the device and then could not be open anymore because seems still always open.

**Comment by eduramiba** [comment] 2022-12-09 14:40
Duplicate of https://github.com/sarxos/webcam-capture/issues/859

**Closed as completed by eduramiba** 2022-12-09 14:40 UTC
